### ISSUE TITLE
[QUESTION] What happened with the original repo?

### ISSUE THREAD

**Issue by fantleas** [szyha/RcloneLabArchive#1]
Title says it all. Do you know anything about why it was removed? This is an extremely useful project. Should we continue where the original developer left off?

Best regards,

**Comment by szyha** [comment]
Unfortunately, but I don't know what happened to the original repository. I will not develop the project.
Greetings.

**Comment by fantleas** [comment]
Ok thanks, and this archive of the project, when was it forked? (for future reference)

**Comment by szyha** [comment]
Yes this is the last version before removal.
