### ISSUE TITLE
How do I sync downloaded files to my Gdrive drive via rclone?[QUESTION]

### ISSUE THREAD

**Issue by baiguke2019** [szyha/RcloneLabArchive#2]
I like your project very much. I won't set it up. Can you give me a tutorial?

**Comment by szyha** [comment]
https://streamable.com/045wu

in minute 1:49 missclick
paste in console - right mouse click
copy folder - write in source folder/*

**Comment by baiguke2019** [comment]
Thank you for the great tutorial and the project is great.
